baseURL = 'https://xjamiex.github.io/database-of-andori'
languageCode = 'en-us'
title = 'THE ANDORI DATABASE'
theme = 'jammuus-terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "red"

  showMenuItems = 1

  [params.banner]
    dismissible = false
    text = "Check it out on GitHub"
    url = "https://github.com/xjamiex/BioTech"


[languages]
  [languages.en.params]
    languageName = "English"
    title = "ğŸ‘ The Andori Database ğŸ‘"
    subtitle = "A blog for the Mindustry mod 'BioTech'"
    owner = "Jammuu"
    keywords = "biotech, mindustry"
    copyright = "MIT"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "HAHA GET ERRORED ON"
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "ğŸ‘ The Andori Database ğŸ‘"
      logoHomeLink = "https://xjamiex.github.io/database-of-andori"

    [[languages.en.menu.main]]
      identifier = "0-0-1"
      name = "Log 0-0-1"
      url = "/0-0-1"